In [4]:
import numpy as np
#1
x = np.ones((5, 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
#2
y = np.zeros((5, 5))
y 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#3
x + y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
#4
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  2
shape =  (5, 5)
size =  25


In [41]:
#5
w = np.array([[11 , 12], [13,14] ,[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [45]:
#6 
z =np.array([[1] ,[2] ,[3]])
z


array([[1],
       [2],
       [3]])

In [46]:
#7
newArray = np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [47]:
#8 
for i in newArray.flat : 
    print(i)

1
11
12
2
13
14
3
15
16


In [48]:
#9
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

In [50]:
#10
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [55]:
#11
print('The smallest value in array',newArray.min())

print('The biggest valuein array',newArray.max())

The smallest value in array 0
The biggest valuein array 15


In [57]:
#12
newArray[0:1]

array([[ 0, 10, 11]])

In [67]:
#13
newArray[1,1]

12

In [184]:
#14
newArray[(0,1),(0,2)]


array([ 0, 13])

In [185]:
#15
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

In [186]:
newArray.reshape(3,2)
#ValueError: cannot reshape array of size 9 into shape (3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)