In [ ]:
"""
Q#1: Create x array with elements equal to 1.
Q#2: Create y array with elements equal to 0.
Q#3: Add x and y arrays.
Q#4: Print x array characteristics (e.g: dimension, shape, size, type)
"""

In [84]:
# Once NumPy is installed on your distribution, to import the NumPy module within your Python session
import numpy as np

In [85]:
x=np.full(5, 0)
x

array([0, 0, 0, 0, 0])

In [86]:
y=np.full(5,1)
y


array([1, 1, 1, 1, 1])

In [87]:
np.add(x, y) 

array([1, 1, 1, 1, 1])

In [34]:
x.dtype

dtype('int32')

In [18]:
x.ndim

1

In [19]:
x.shape


(5,)

In [20]:
x.size

5

In [ ]:
""""
Q#5: Create a 2D array "called w" as the following:
11	12
13	14
15	16
Q#6: Create z array contains the numbers from 1 to 3.
Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".
Q#8: Print all elements of "newArray" using the loop.
Q#9: Reverse the columns and rows of "newArray".
Q#10: Decrement all elements of "newArray" with 1.
Q#11: Find smallest and biggest values in "newArray".
Q#12: Print the first row of "newArray" using indexing.
""""

In [98]:
w= np.array([[11, 12], [13,14], [15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [99]:
z=np.arange(1,4)
z

array([1, 2, 3])

In [100]:
newArray=np.column_stack((w,z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

In [101]:
for item in newArray.flat:
    print(item)

11
12
1
13
14
2
15
16
3


In [102]:
newArray=newArray.transpose()
newArray

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

In [103]:
newArray=np.subtract(newArray,1)
newArray

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

In [104]:
print(newArray.min())

0


In [129]:
print(newArray.max())

15


In [128]:
newArray[0,:]

array([10, 12, 14])

In [ ]:
"""
Q#13: Print the number equals 12 of "newArray" using indexing.
Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.
Q#15: Change the shape of "newArray" to (9,1).
Q#16: Change the shape of "newArray" to (3,2).

"""

In [131]:
newArray[0,1]

12

In [138]:
newArray[2,0]

0

In [139]:
newArray[1,1]

13

In [145]:
newArray.reshape(9,1)


array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

In [149]:
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)