In [2]:
import numpy as np

In [254]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [255]:
#Create y array with elements equal to 0.
y=np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [256]:
## Q#3: Add x and y arrays.
add=np.add(x,y)
add

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [257]:
## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  2
shape =  (3, 3)
size =  9


In [259]:
## Q#5: Create a 2D array "called w" as the following:

w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [266]:
## Q#6: Create z array contains the numbers from 1 to 3.
z=np.arange(1,3)
z

array([1, 2])

In [291]:
## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".
newArray= np.vstack((z,w))
newArray

array([[ 1,  2],
       [11, 12],
       [13, 14],
       [15, 16]])

In [292]:
## Q#8: Print all elements of "newArray" using the loop.
for i in newArray:
    print(i)

[1 2]
[11 12]
[13 14]
[15 16]


In [293]:
## Q#9: Reverse the columns and rows of "newArray".
newArray.transpose()

array([[ 1, 11, 13, 15],
       [ 2, 12, 14, 16]])

In [294]:
## Q#10: Decrement all elements of "newArray" with 1.
newArray =np.subtract(newArray,1)
newArray

array([[ 0,  1],
       [10, 11],
       [12, 13],
       [14, 15]])

In [295]:
## Q#11: Find smallest and biggest values in "newArray". 
newArray.min()


0

In [296]:
newArray.max()

15

In [297]:
## Q#12: Print the first row of "newArray" using indexing.
newArray[0][0]

0

In [298]:
## Q#13: Print the number equals 12 of "newArray" using indexing.
newArray[2][0]

12

In [299]:
## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.
newArray[0:3,0:2]

array([[ 0,  1],
       [10, 11],
       [12, 13]])

In [305]:
newArray.reshape(8,1)

array([[ 0],
       [ 1],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [306]:
newArray.size

8

In [307]:
newArray.shape

(4, 2)

In [243]:
## Q#16: Change the shape of "newArray" to (3,2).
newArrayy.reshape(3,2)

ValueError: cannot reshape array of size 10 into shape (3,2)

array([[1., 1.],
       [1., 1.]])

# Well Done 🎉