In [164]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [165]:
x = np.ones((3))
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [166]:
y = np.zeros((3))
y

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [167]:
x + y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [168]:
print("Dimensions of x = ", x.ndim)
print("Shape of x = ", x.shape)
print("Size of x = ", x.size)
print("Type of x = ", x.dtype)

Dimensions of x =  1
Shape of x =  (3,)
Size of x =  3
Type of x =  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [169]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [170]:
w.shape

(3, 2)

## Q#6: Create z array contains the numbers from 1 to 3.

In [171]:
z = np.arange(1,4)
z

array([1, 2, 3])

In [172]:
z.shape

(3,)

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [173]:
newArray = np.column_stack((w,z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [174]:
for value in newArray.flat:
    print(value)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [175]:
newArray.transpose()

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [176]:
newArray = newArray - 1

## Q#11: Find smallest and biggest values in "newArray".

In [177]:
newArray.min()

0

In [178]:
newArray.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [179]:
newArray[0]

array([10, 11,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [180]:
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

In [181]:
newArray[newArray == 12]

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [182]:
newArray[[0,1],[2,1]] #[row,row],[column,column]

array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [183]:
newArray.reshape((9,1))

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [205]:
np.resize(newArray,(3,2)) 

array([[10, 11],
       [ 0, 12],
       [13,  1]])

# Well Done 🎉