In [85]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [88]:
x= np.ones(7)
x

array([1., 1., 1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [87]:
y = np.zeros(7)
y

array([0., 0., 0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [ ]:
resolt = np.add(x,y)
print(resolt)

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [ ]:
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [154]:
w = np.array(np.arange(11,17).reshape(3,2))
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [152]:
z = np.array(np.arange(1,4))
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [155]:
newArray = np.vstack([z, w.reshape(2,3)])
print(newArray)

[[ 1  2  3]
 [11 12 13]
 [14 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [156]:
for i in newArray:
    for item in i:
        print(item)
    

1
2
3
11
12
13
14
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [157]:
newArray.transpose()

array([[ 1, 11, 14],
       [ 2, 12, 15],
       [ 3, 13, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [158]:
newArray=newArray-1
print(newArray)

[[ 0  1  2]
 [10 11 12]
 [13 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [159]:
newArray.min()

0

## Q#12: Print the first row of "newArray" using indexing.

In [160]:
newArray[0]

array([0, 1, 2])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [161]:
newArray[newArray==12]

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [162]:
print(newArray[np.where(newArray == 0)])
print(newArray[np.where(newArray == 13)])

[0]
[13]


## Q#15: Change the shape of "newArray" to (9,1).

In [163]:
newArray.reshape(9,1)

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [164]:
erorr

NameError: name 'erorr' is not defined

# Well Done 🎉