In [ ]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [ ]:
x = np.ones((3))
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [ ]:
y = np.zeros((3))
y

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [ ]:
x + y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [ ]:
print("Dimensions of x = ", x.ndim)
print("Shape of x = ", x.shape)
print("Size of x = ", x.size)
print("Type of x = ", x.dtype)

Dimensions of x =  1
Shape of x =  (3,)
Size of x =  3
Type of x =  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [ ]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
w.shape

(3, 2)

## Q#6: Create z array contains the numbers from 1 to 3.

In [ ]:
z = np.arange(1,4)
z

array([1, 2, 3])

In [ ]:
z.shape

(3,)

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [ ]:
newArray = np.column_stack((w,z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [ ]:
for value in newArray.flat:
    print(value)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [ ]:
newArray.transpose()

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [ ]:
newArray = newArray - 1

## Q#11: Find smallest and biggest values in "newArray".

In [ ]:
newArray.min()

0

In [ ]:
newArray.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [ ]:
newArray[0]

array([10, 11,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [ ]:
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

In [ ]:
newArray[newArray == 12]

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [ ]:
newArray[[0,1],[2,1]] #[row,row],[column,column]

array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [ ]:
newArray.reshape((9,1))

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [ ]:
np.resize(newArray,(3,2)) #lossing the last 3 elements [14,15,2]
""" resize will remove some of the element resulting in 
    losing some of the data unlike the reshape which will 
    reshape the original data without removing any element
    reshape in this case is not applicable due to the variety
    of the dimensions """

array([[10, 11],
       [ 0, 12],
       [13,  1]])

# Well Done 🎉