In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x = np.array(np.ones((3, 3)))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [4]:
y = np.array(np.zeros((3, 3)))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [5]:
a = x + y
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [6]:
print(x.size, x.shape, x.dtype, x.ndim)

9 (3, 3) float64 2


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [7]:
w = np.array([[11,12], [13,14], [15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [8]:
z = np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [9]:
newArray = np.column_stack((z, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [10]:
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [11]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [12]:
newArray -=1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [13]:
print(newArray.max())
print(newArray.min())

15
0


## Q#12: Print the first row of "newArray" using indexing.

In [14]:

print(a[1])

[1. 1. 1.]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [15]:
newArray
print(newArray[0, 1])

10


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [23]:
newArray
print(newArray[0, 0])
print(newArray[1, 2])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [24]:
newArray.reshape(9, 1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [25]:
newArray.reshape(3, 2)
# it cant be done

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉