In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
x=np.array([1,1,1])

## Q#2: Create y array with elements equal to 0.

In [5]:
y=np.array([0,0,0])

## Q#3: Add x and y arrays.

In [6]:
x+y

array([1, 1, 1])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [11]:
x.ndim

1

In [12]:
x.shape

(3,)

In [13]:
x.size

3

In [14]:
x.dtype

dtype('int32')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [16]:
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [27]:
z=np.arange(1,3)
z

array([1, 2])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [29]:
newArray=np.vstack([w,z])
newArray

array([[11, 12],
       [13, 14],
       [15, 16],
       [ 1,  2]])

## Q#8: Print all elements of "newArray" using the loop.

In [30]:
for row in newArray:
    for item in row:
        print(item)

11
12
13
14
15
16
1
2


## Q#9: Reverse the columns and rows of "newArray".

In [31]:
newArray.T

array([[11, 13, 15,  1],
       [12, 14, 16,  2]])

## Q#10: Decrement all elements of "newArray" with 1.

In [32]:
newArray+1

array([[12, 13],
       [14, 15],
       [16, 17],
       [ 2,  3]])

## Q#11: Find smallest and biggest values in "newArray".

In [35]:
np.min(newArray)

1

In [36]:
np.max(newArray)

16

## Q#12: Print the first row of "newArray" using indexing.

In [37]:
newArray[0,:]

array([11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [38]:
newArray[newArray == 12]

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [41]:
newArray[(newArray == 0 ) | (newArray == 13)]

array([13])

## Q#15: Change the shape of "newArray" to (9,1).

In [43]:
# can't change to (9,1) becuase the size is 8 so i change it to (8,1)
newArray.reshape([8,1])

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [45]:
# can't change to (3,2) becuase the size is 8 so i change it to (4,2)
newArray.reshape([4,2])

array([[11, 12],
       [13, 14],
       [15, 16],
       [ 1,  2]])

# Well Done 🎉