In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [4]:
y = np.zeros((5,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Q#3: Add x and y arrays.

In [5]:
x + y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [6]:
print(x.shape)
print(x.size)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

(5, 5)
25
2
float64
8


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [7]:
w = np.arange(11,17).reshape((3,2))
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [8]:
z = np.arange(1,4).reshape((3,1))
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [9]:
newArray = np.hstack((w,z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [10]:
for row in newArray:
    for i in row:
        print(i)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [11]:
newArray.transpose()

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [12]:
newArray -= 1
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [13]:
print(newArray.min())
print(newArray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [14]:
newArray[0][:]

array([10, 11,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [15]:
newArray[1,0]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [16]:
newArray[[0,1], [2,1]]

array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [17]:
newArray.reshape((9,1))
newArray.size

9

## Q#16: Change the shape of "newArray" to (3,2).

> THERE IS NO ANSWER

In [18]:
newArray.reshape((3,2))

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉