In [1]:
import numpy as np


In [6]:
x=np.ones((3,3))


In [7]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
y=np.zeros((3, 3))

In [9]:
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
x+y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Print x array characteristics (e.g: dimension, shape, size, type)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)
print('type = ', x.dtype)

number of dimensions =  2
shape =  (3, 3)
size =  9
type =  float64


In [43]:
# Create a 2D array "called w" as the following:
#11	12
#13	14
#15	16
w = np.array([[11, 12], [13,14],[15,16]])
w


array([[11, 12],
       [13, 14],
       [15, 16]])

In [61]:
z = np.arange(1,3)
z

array([1, 2])

In [63]:
# Combine the arrays z and w in vertical way then save it in a new variable "newArray"
newArray=np.vstack((z, w))
newArray

array([[ 1,  2],
       [11, 12],
       [13, 14],
       [15, 16]])

In [65]:
# Print all elements of "newArray" using the loop.
for row in newArray :
    for item in row:
        print(item)

1
2
11
12
13
14
15
16


In [68]:
#Reverse the columns and rows of "newArray"
newArray=np.flipud(newArray)
newArray

array([[ 1,  2],
       [11, 12],
       [13, 14],
       [15, 16]])

In [69]:
 #Decrement all elements of "newArray" with 1.
newArray-= 1
newArray

array([[ 0,  1],
       [10, 11],
       [12, 13],
       [14, 15]])

In [71]:
#Find smallest and biggest values in "newArray
newArray.min()


0

In [72]:
newArray.max()

15

In [73]:
# Print the first row of "newArray" using indexing
newArray[0]

array([0, 1])

In [75]:
#Print the number equals 12 of "newArray" using indexing
newArray[2][0]

12

In [114]:
#Print the numbers equal 0 and 13 of "newArray" using Slicing
newArray[0, 0:-1]


array([0])

In [113]:
newArray[2,-1:2]

array([13])

In [112]:
#Change the shape of "newArray" to (9,1)
x=newArray.reshape(8,1)
x

array([[ 0],
       [ 1],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
#Change the shape of "newArray" to (3,2).
no answer