In [178]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [179]:
x=np.array(np.ones((3,3)))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [180]:
y=np.array(np.zeros((3,3)))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [181]:
a =x+y
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [182]:
x.ndim


2

In [183]:
x.shape


(3, 3)

In [184]:
x.size

9

In [185]:
x.dtype

dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [186]:
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [187]:
z=np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [207]:
newArray = np.column_stack((z, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [202]:
for row in newarray:
    for a in row:
        print(a)

-2
8
9
-1
10
11
0
12
13


## Q#9: Reverse the columns and rows of "newArray".

In [190]:
newarray.transpose()

array([[-1,  9, 10,  0, 11, 12,  1, 13, 14]])

In [191]:
#10: Decrement all elements of "newArray" with 1.

In [192]:
newarray-=1
newarray


array([[-2],
       [ 8],
       [ 9],
       [-1],
       [10],
       [11],
       [ 0],
       [12],
       [13]])

## Q#11: Find smallest and biggest values in "newArray".

In [193]:
np.min(newarray)


-2

In [194]:
np.max(newarray)


13

## Q#12: Print the first row of "newArray" using indexing.

In [195]:
newarray[0,:]


array([-2])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [196]:
newarray[newarray == 12]


array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [197]:
newarray[(newarray == 0 ) | (newarray == 13)]


array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [198]:
newarray.shape = (9 , 1)
newarray

array([[-2],
       [ 8],
       [ 9],
       [-1],
       [10],
       [11],
       [ 0],
       [12],
       [13]])

## Q#16: Change the shape of "newArray" to (3,2).

In [199]:
# cannot reshape array of size 9 into shape (3,2) ,  



# Well Done 🎉