In [142]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [143]:
x = np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [144]:
y = np.zeros((2,2))

## Q#3: Add x and y arrays.

In [145]:
z = x + y
z

array([[1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [146]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 2)
4
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [147]:
w = np.array([
    [11, 12],  
    [13, 14],
    [15, 16]
])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [148]:
z = np.arange(1, 4).reshape(3,1)
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [149]:
newArray = np.hstack((z,w ))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [150]:
for row in newArray:
    for item in row:
        print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [151]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [152]:
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [153]:
newArray.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [154]:
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [155]:
print(newArray[[1],[1]])


#هنا تحمست شوي ما فهمت السؤال ولكن احتياط راح اترك الحل
for row in newArray:
    for item in row:    
        if item == 12:
            print(item)

[12]
12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [156]:

print(newArray[0:2])

[[ 0 10 11]
 [ 1 12 13]]


## Q#15: Change the shape of "newArray" to (9,1).

In [157]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [189]:
[SplitArray1, SplitArray2, SplitArray3] = np.split(newArray,[0,1],axis=1)
SplitArray3

array([[10, 11],
       [12, 13],
       [14, 15]])

# Well Done 🎉