In [6]:
import numpy as np
#Q1: Create x array with elements equal to 1.
x=np.ones ((5,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
#Q2: Create y array with elements equal to 0.
y=np.zeros ((5,5))
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#Q3: Add x and y arrays.
x +y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
#Q4: Print x array characteristics (e.g: dimension, shape, size, type)
print ('type =', x.dtype)
print ('Number of dim =', x.ndim)
print ('Shape =', x.shape)
print ('size =', x.size)

type = float64
Number of dim = 2
Shape = (5, 5)
size = 25


In [31]:
#Q5 Create a 2D array "called w" as the following:
w= np.array([[11,12],[13,14,],[15,16]])
w.shape

(3, 2)

In [36]:
#Q6: Create z array contains the numbers from 1 to 3
z=np.array([[1],[2],[3]])
z

array([[1],
       [2],
       [3]])

In [35]:
#Q7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".
newArray=np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [38]:
#Q8: Print all elements of "newArray" using the loop.
for row in newArray:
    for item in row:
        print(item)

1
11
12
2
13
14
3
15
16


In [40]:
#Q9: Reverse the columns and rows of "newArray".
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

In [43]:
#Q10: Decrement all elements of "newArray" with 1.
newArray-=1
newArray

array([[-2,  8,  9],
       [-1, 10, 11],
       [ 0, 12, 13]])

In [45]:
#Q11: Find smallest and biggest values in "newArray".
newArray.min()
newArray.max()

13

In [47]:
#Q12 Print the first row of "newArray" using indexing.
newArray[0]

array([-2,  8,  9])

In [51]:
#Q13: Print the number equals 12 of "newArray" using indexing.
newArray[2,1]


12

In [113]:
#Q14: Print the numbers equal 0 and 13 of "newArray" using Slicing.
print(newArray[2:,:1]) 
print(newArray[2:, 2:3])

[[0]]
[[13]]


In [115]:
#Q15: Change the shape of "newArray" to (9,1).
newArray.shape=(9,1)
newArray


array([[-2],
       [ 8],
       [ 9],
       [-1],
       [10],
       [11],
       [ 0],
       [12],
       [13]])

In [117]:
#Q16: Change the shape of "newArray" to (3,2).
newArray.shape=(3,2)
newArray

#cannot reshape array of size 9 into shape (3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)