In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [7]:
x = np.array([11,13,15])


## Q#2: Create y array with elements equal to 0.

In [8]:
y = np.array([12,14,16])


## Q#3: Add x and y arrays.

In [11]:
np.add(x,y)

array([23, 27, 31])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [15]:
x.ndim

1

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [61]:

w = np.array([[11,12],[13,14],[15,16]])

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [62]:
z = np.arange(1,4)

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [66]:
res = np.column_stack((z,w))

## Q#8: Print all elements of "newArray" using the loop.

In [67]:
res

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#9: Reverse the columns and rows of "newArray".

In [69]:
np.flip(res)

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [90]:
res+1

array([[ 2, 12, 13],
       [ 3, 14, 15],
       [ 4, 16, 17]])

## Q#11: Find smallest and biggest values in "newArray".

In [91]:
res.min()
res.max()

16

## Q#12: Print the first row of "newArray" using indexing.

In [92]:
res[0]

array([ 1, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [94]:
res[0,2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [102]:
res[:2]

array([[ 1, 11, 12],
       [ 2, 13, 14]])

## Q#15: Change the shape of "newArray" to (9,1).

In [103]:
res.reshape(9,1)

array([[ 1],
       [11],
       [12],
       [ 2],
       [13],
       [14],
       [ 3],
       [15],
       [16]])

## Q#16: Change the shape of "newArray" to (3,2).

In [110]:
#can't doing that

# Well Done 🎉